-- MySQL Script generated by MySQL Workbench
-- Mon Oct 13 11:54:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FelixFitness
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FelixFitness
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FelixFitness` ;
USE `FelixFitness` ;

-- -----------------------------------------------------
-- Table `FelixFitness`.`planoTreino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FelixFitness`.`planoTreino` (
  `tipo` VARCHAR(45) NOT NULL,
  `idplanoTreino` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `valorMensal` FLOAT NOT NULL COMMENT '	',
  `quantidadeTreinoSemana` INT NOT NULL,
  `beneficios` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idplanoTreino`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FelixFitness`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FelixFitness`.`Aluno` (
  `idAluno` INT NOT NULL,
  `nomeCompleto` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `matricula` INT NOT NULL,
  `planoTreino_idplanoTreino` INT NOT NULL,
  PRIMARY KEY (`idAluno`, `planoTreino_idplanoTreino`),
  INDEX `fk_Aluno_planoTreino_idx` (`planoTreino_idplanoTreino` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_planoTreino`
    FOREIGN KEY (`planoTreino_idplanoTreino`)
    REFERENCES `FelixFitness`.`planoTreino` (`idplanoTreino`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FelixFitness`.`Instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FelixFitness`.`Instrutor` (
  `idInstrutor` INT NOT NULL,
  `cref` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `especialidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInstrutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FelixFitness`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FelixFitness`.`Avaliacao` (
  `idAvaliacao` INT NOT NULL,
  `dataAvaliacao` DATE NOT NULL,
  `peso` FLOAT NOT NULL,
  `altura` FLOAT NOT NULL,
  `percentualGordura` FLOAT NOT NULL,
  `imc` FLOAT NOT NULL,
  `Instrutor_idInstrutor` INT NOT NULL,
  `Aluno_idAluno` INT NOT NULL,
  PRIMARY KEY (`idAvaliacao`, `Instrutor_idInstrutor`, `Aluno_idAluno`),
  INDEX `fk_Avaliacao_Instrutor1_idx` (`Instrutor_idInstrutor` ASC) VISIBLE,
  INDEX `fk_Avaliacao_Aluno1_idx` (`Aluno_idAluno` ASC) VISIBLE,
  CONSTRAINT `fk_Avaliacao_Instrutor1`
    FOREIGN KEY (`Instrutor_idInstrutor`)
    REFERENCES `FelixFitness`.`Instrutor` (`idInstrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `FelixFitness`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FelixFitness`.`Aluno_has_Instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FelixFitness`.`Aluno_has_Instrutor` (
  `Aluno_idAluno` INT NOT NULL,
  `Instrutor_idInstrutor` INT NOT NULL,
  PRIMARY KEY (`Aluno_idAluno`, `Instrutor_idInstrutor`),
  INDEX `fk_Aluno_has_Instrutor_Instrutor1_idx` (`Instrutor_idInstrutor` ASC) VISIBLE,
  INDEX `fk_Aluno_has_Instrutor_Aluno1_idx` (`Aluno_idAluno` ASC) VISIBLE,
  CONSTRAINT `fk_Aluno_has_Instrutor_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `FelixFitness`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Instrutor_Instrutor1`
    FOREIGN KEY (`Instrutor_idInstrutor`)
    REFERENCES `FelixFitness`.`Instrutor` (`idInstrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FelixFitness`.`Treino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FelixFitness`.`Treino` (
  `idTreino` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `nivelDificuldade` VARCHAR(45) NOT NULL,
  `Instrutor_idInstrutor` INT NOT NULL,
  PRIMARY KEY (`idTreino`, `Instrutor_idInstrutor`),
  INDEX `fk_Treino_Instrutor1_idx` (`Instrutor_idInstrutor` ASC) VISIBLE,
  CONSTRAINT `fk_Treino_Instrutor1`
    FOREIGN KEY (`Instrutor_idInstrutor`)
    REFERENCES `FelixFitness`.`Instrutor` (`idInstrutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FelixFitness`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FelixFitness`.`Pagamento` (
  `idPagamento` INT NOT NULL,
  `dataPagamento` DATE NOT NULL,
  `valorPago` FLOAT NOT NULL,
  `formaPagamento` VARCHAR(45) NOT NULL,
  `mesReferencia` DATE NOT NULL,
  `Aluno_idAluno` INT NOT NULL,
  PRIMARY KEY (`idPagamento`, `Aluno_idAluno`),
  INDEX `fk_Pagamento_Aluno1_idx` (`Aluno_idAluno` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `FelixFitness`.`Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
