-- MySQL Script generated by MySQL Workbench
-- Mon Oct  6 11:12:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema School
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema School
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `School` ;
USE `School` ;

-- -----------------------------------------------------
-- Table `School`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `School`.`Student` (
  `idStudent` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `birthDate` DATE NOT NULL,
  PRIMARY KEY (`idStudent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `School`.`Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `School`.`Subject` (
  `idSubject` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `load` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSubject`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `School`.`Do`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `School`.`Do` (
  `Student_idStudent` INT NOT NULL,
  `Subject_idSubject` INT NOT NULL,
  PRIMARY KEY (`Student_idStudent`, `Subject_idSubject`),
  INDEX `fk_Student_has_Subject_Subject1_idx` (`Subject_idSubject` ASC) VISIBLE,
  INDEX `fk_Student_has_Subject_Student_idx` (`Student_idStudent` ASC) VISIBLE,
  CONSTRAINT `fk_Student_has_Subject_Student`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `School`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Subject_Subject1`
    FOREIGN KEY (`Subject_idSubject`)
    REFERENCES `School`.`Subject` (`idSubject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
